In [5]:
import numpy as np
import pandas as pd
import datetime as dt
from vnstock import *
import requests

In [22]:
listing = pd.read_excel('listing.xlsx')

In [ ]:
listing.to_excel('listing.xlsx')

In [24]:
overview = []
for i in listing['ticker']:
    i_overview = ticker_overview(i).values.tolist()
    overview += i_overview

KeyboardInterrupt:

In [ ]:
overview_df = pd.DataFrame(overview, columns = ticker_overview('SHS').columns)

In [ ]:
overview_df.head()

In [ ]:
overview_df.to_excel('overview.xlsx')

In [31]:
price_board('TCB,SSI,VND')

,Mã CP,Giá Khớp Lệnh,KLBD/TB5D,T.độ GD,KLGD ròng(CM),%KLGD ròng (CM),RSI,MACD Volume,MACD Signal,Tín hiệu KT,...,Khối lượng Dư mua,Khối lượng Dư bán,Khớp nhiều nhất,seq,vnid3d,vnid1m,vnid3m,vnid1y,vnipe,vnipb
0,TCB,28350.0,1.66,2.02,-85200,-19.7,61.260158,0.21,Buy,Buy,...,404600,1085600,28350,1680249540,0.5,3.7,5.0,-29.3,12.0036,1.58003
1,SSI,21500.0,1.60,6.34,3155800,40.3,63.750656,0.15,Buy,Sell,...,286100,1872300,21500,1680249540,0.5,3.7,5.0,-29.3,12.0036,1.58003
2,VND,15500.0,1.37,4.80,1489100,22.7,58.532234,0.08,Neutral,Neutral,...,679300,1857500,15500,1680249540,0.5,3.7,5.0,-29.3,12.0036,1.58003

In [36]:
%%time
price = []
for i in listing['ticker']:
    i_price = price_board(i).values.tolist()
    price += i_price

Wall time: 8min 2s

In [37]:
price_df = pd.DataFrame(price, columns = price_board('SHS').columns)

In [38]:
price_df

,Mã CP,Giá Khớp Lệnh,KLBD/TB5D,T.độ GD,KLGD ròng(CM),%KLGD ròng (CM),RSI,MACD Volume,MACD Signal,Tín hiệu KT,...,Khối lượng Dư mua,Khối lượng Dư bán,Khớp nhiều nhất,seq,vnid3d,vnid1m,vnid3m,vnid1y,vnipe,vnipb
0,VVS,0.0,0.00,0.00,0.0,0.0,0.000000,0.00,,,...,3100.0,7300.0,0.0,1.680250e+09,0.5,3.7,5.0,-29.3,12.0036,1.58003
1,XDC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,...,NaN,NaN,NaN,NaN,0.5,3.7,5.0,-29.3,12.0036,1.58003
2,HSV,3800.0,9.09,0.00,0.0,0.0,48.333286,0.01,Neutral,Sell,...,2700.0,10100.0,3800.0,1.680250e+09,0.5,3.7,5.0,-29.3,12.0036,1.58003
3,CST,20900.0,2.07,1.31,0.0,0.0,47.646562,-0.02,Sell,Sell,...,54200.0,18600.0,21300.0,1.680250e+09,0.5,3.7,5.0,-29.3,12.0036,1.58003
4,BVL,9900.0,0.42,0.00,0.0,0.0,38.010711,-0.08,Neutral,Buy,...,2900.0,4000.0,9900.0,1.680250e+09,0.5,3.7,5.0,-29.3,12.0036,1.58003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1619,XMP,18400.0,0.28,0.00,0.0,0.0,53.274068,0.07,Buy,Buy,...,400.0,10200.0,18400.0,1.680250e+09,0.5,3.7,5.0,-29.3,12.0036,1.58003
1620,YBC,0.0,0.00,0.00,0.0,0.0,0.000000,0.00,,,...,0.0,1600.0,0.0,1.680250e+09,0.5,3.7,5.0,-29.3,12.0036,1.58003
1621,YBM,6050.0,0.10,0.00,0.0,0.0,58.258814,0.04,Neutral,Buy,...,3300.0,50500.0,5900.0,1.680250e+09,0.5,3.7,5.0,-29.3,12.0036,1.58003
1622,YEG,9980.0,0.48,0.48,0.0,0.0,46.053402,-0.08,Neutral,Neutral,...,9600.0,9200.0,9920.0,1.680250e+09,0.5,3.7,5.0,-29.3,12.0036,1.58003
1623,YTC,0.0,0.00,0.00,0.0,0.0,0.000000,0.00,,,...,0.0,12500.0,0.0,1.680250e+09,0.5,3.7,5.0,-29.3,12.0036,1.58003

In [39]:
price_df.to_excel('price_df.xlsx')

In [50]:
financial_flow(symbol="SGN", report_type='cashflow', report_range='quarterly')

        ticker  investCost  fromInvest  fromFinancial  fromSale  freeCashFlow
index
2022-Q4    SGN          -5        -172              0        75         286.0
2022-Q3    SGN          -3         101            -84        43         147.0
2022-Q2    SGN           0         -49              0        71         109.0
2022-Q1    SGN           0        -188              0        -4         143.0
2021-Q4    SGN           0           2            -84       161         145.0
2021-Q3    SGN           0           2              0       -10         105.0
2021-Q2    SGN           0           2              0        22         120.0
2021-Q1    SGN           0           2              0        15         137.0
2020-Q4    SGN          62         194           -141        25         196.0
2020-Q3    SGN         -62         -97             -7        44         139.0
2020-Q2    SGN         -37          16              0       -38         331.0
2020-Q1    SGN         -74         -69              0        44         331.0
2019-Q4    SGN         -61         -55              0        43         308.0
2019-Q3    SGN         -74         -75             -7       116         235.0
2019-Q2    SGN         -39         -37            -72       137         222.0
2019-Q1    SGN         -40         -39              0        26         331.0
2018-Q4    SGN         -68         -76             20        95         248.0
2018-Q3    SGN           0           2              0       107         254.0
2018-Q2    SGN           2           3            -77       104         242.0
2018-Q1    SGN          -2           9              0        68         286.0
2017-Q4    SGN         -31         -30              0        57          81.0
2017-Q4    SGN         -31         -30              0        57         208.0
2017-Q3    SGN         -16         -15            -78        99         139.0
2017-Q2    SGN         -64         -84              0        82         149.0
2017-Q1    SGN         -46         -26             15        35         199.0
2016-Q4    SGN         -61         -20            -21        34         -30.0
2016-Q3    SGN           7         -42              1        65         159.0
2016-Q2    SGN         -33         -43              0        66           NaN
2016-Q1    SGN         -51         -51              0        40           NaN
2015-Q4    SGN         -23         -43            -14        54         310.0
2014-Q1    SGN         -22         -22              0        40           NaN